### ISSUE TITLE
Typescript Style Checker

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-webapp#10]
Since we have implemented an automated style checking process for the scala code of this project, it might be worth looking into something similar for angular's typescript code, which will be added to this repository. 

Some possibilities I already know about are:  
https://github.com/google/ts-style
https://github.com/palantir/tslint
https://github.com/mgechev/codelyzer

@bhermann do we need something like this?
@nguyenLisa  do we already have something similar in place/planed for abm-frontend, which we could reuse, or is this interesting for you too?

**Comment by bhermann** [comment]
Good point... Yes we will need that.

**Comment by janniclas** [comment]
We already took a first look at it and executed some local style checking with codelyzer, which looked promising. 
We still need to figure out how to include it in the automatic check process and use it in IDEs. We will update this issue / create a pull request once we have a complete solution.

**Comment by nguyenLisa** [comment]
Sorry for the late answer, yes, we will need that for abm and abm-frontend as well. @ankur-1989 is working on that and will coordinate with the ABM team. Let us know when you have updates :)

**Comment by bhermann** [comment]
@janniclas This is completed, right?

**Comment by janniclas** [comment]
yes, I believe we are set with the current rules. no real point in keeping this open just for possible additions.
