### ISSUE TITLE
Link on the start screen for a Delphi wiki page

### ISSUE THREAD

**Issue by anitha181992** [delphi-hub/delphi-webapp#13]
Right now to understand the workflow for Delphi we access Git Readmd, to make it more clear, we can build a wiki document for Delphi, explaining the current architecture, what each of the component does , links to the issues being worked on, future scope for Delphi.
Have the link of this wiki on the start up screen.

Reason: While we started working on Delphi, it was quite confusing to get a whole picture of the architecture, so this issue might help to resolve it.

**Comment by bhermann** [comment]
Completed as part of the ongoing project group.
