### ISSUE TITLE
Getting error for some queries from the api "https://delphi.cs.uni-paderborn.de/api/search"

### ISSUE THREAD

**Issue by mgupta0421** [delphi-hub/delphi-webapp#32]
**Describe the bug**
A User is getting the error or cannot receive the correct result for the below queries for the projects 'delphi-cli' and ABM

**To Reproduce**

Project- Delphi-cli
1. Run sbt run on the project 'delphi-cli' 
2. Type the query with the command  "delphi search "query" "
3. See the error or the result(which are not correct)

Project- ABM
1. Login on the application ABM, navigate to the url 'https://abm.cs.upb.de/search' and search for the below given queries.
2. See the error or the result(which are not correct)

 Queries-
1- "[Using KeyStore]>10&&[Using KeyStore]<25"
2. "[Using KeyStore]>10||[Using KeyStore]<40"

**Expected behavior**
It should give the result for the queries

**Affected components (if known)**
Choose those applicable here:, webapi, cli, ABM, webapp

**Desktop (please complete the following information, if relevant):**

**Comment by mgupta0421** [comment]
Just a heads-up on this issue. Ben, did you get the chance to look into it.

**Comment by bhermann** [comment]
These will work in `webapi` version >= 0.9.5

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Thank you Ben for the update and closure😃
