### ISSUE TITLE
Story: As a registered user, I would like to be able to name and save (and load) a query

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-webapp#4]
**Is your feature request related to a problem? Please describe.**
Delphi queries might become pretty complex. 
Saving them on an external pad will be pretty tiresome at some point.

**Describe the solution you'd like**
As a registered user, I would like to be able to save a query with a name. 
I also would like to be able to load this query into the current editing/run environment. 

**Describe alternatives you've considered**
None

**Additional context**
Suggested by @janniclas and @johannesduesing as part of the PG 2018/2019 course.

**Comment by Shashank-KanakapuraSrivatsa** [comment]
This issue is addressed with new UI.. PR #69 includes this feature..
