### ISSUE TITLE
Front-end validations

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#41]
**Description**
input validations in the front-end application

**Status** 
Has dependency on back-end validations

**Comment by Subbup101** [comment]
Working with backend team to get the necessary error messages and invalid query suggestions for validation.

**Comment by Subbup101** [comment]
Validations like req field validator and query syntax validator has been implemented

**Comment by Subbup101** [comment]
Awaiting metric validator implementation in backend to re-use it in front-end side.

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #67
