### ISSUE TITLE
Auto-completion feature

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#42]
**Description**
Input query auto-completion feature. When the user types the input query, auto-complete feature gives suggestion to complete the query. 

**Status**
Results are fetched and waiting for front-end implementation

**Comment by syam595** [comment]
Created three intermediatory milestones for the autocompletion enhancement

--> Build Corpus
--> UI Implementation
--> Use of Validation APIs

Started with "Build Corpus" milestone

**Comment by syam595** [comment]
Completed the Build Corpus milestone
--> Used the feature API
--> Included the operators

Started the UI implementation milestone

**Comment by syam595** [comment]
Working on the UI implementation. Current autocomplete libraries extends the v-select attribute in vue js. But the project uses text area, so working on implementing the same for text area.

**Comment by syam595** [comment]
UI implementation is almost completed.
Fixing some bugs in the implementation

**Comment by syam595** [comment]
UI implementation is completed and integrated with the new UI cahnges.
Raised a PR : https://github.com/delphi-hub/delphi-webapp/pull/70

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #70
