### ISSUE TITLE
UI changes - bug fixes and UI beautification

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#43]
**Description**
Minor corrections in UI to make the page more responsive and enhancing the look and feel of the page

**Status **
Has been discussed with the team and is in initial phase

**Comment by SViktorS** [comment]
Status as on : 22 Jan 2020

Completed
--> When the window size is decreased, the logo will stay at its place
--> Was thinking about design changes. Will present them tomorrow.

**Comment by SViktorS** [comment]
Status on 26.02.2020

Completed new Interface from my side. Next step will be merging it with current develop branch locally and afterwards raising a pr.

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #69
