### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#45]
**Description**
Input validations in back-end

**Status**
In progress

**Comment by mgupta0421** [comment]
Backend validation is done and right now in the testing phase.

**Comment by seena-mathew** [comment]
Testing for the backend validation has been performed. The current codes for validation of query does not include validating the metric names.
Validation of Metric names in backend is in progress .

**Comment by mgupta0421** [comment]
Validation of query in terms of Syntax has been done and raised in PR# 61

**Comment by mgupta0421** [comment]
Done -> Validation of query in terms of Syntax
Accepted in PR# 61

**Comment by mgupta0421** [comment]
Feature validation has been done and raised in PR# 67

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #67
