### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#47]
**Description**
Handling the errors and displaying suitable error messages

**Status**
In progress

**Comment by chinmayk1613** [comment]
Update_22.01.2020
--- analysis done for what and how status code and status message is being displayed.
--- detemined the exact location where this functionality needs to be implemented.

**Comment by chinmayk1613** [comment]
Update_29.01.2020
---- Successfully fetch the response code from HttpResponse and display via only back-end.
---- Need to test with frontEnd whether is can be forwarded to their end or not.

**Comment by chinmayk1613** [comment]
Update_04.02.2020
---- Fetch the response code in Result Object.
---- tested with applicaton and successfully printed in console.

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #64
