### ISSUE TITLE
Testing - Front-end 

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#48]
**Description**
Testing the newly developed GUI and its functionalities

**Status **
Being planned. Test cases yet to be developed

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Status as on : 13 Feb 2020 

Testing frameworks are being explored

**Comment by syam595** [comment]
@Subbup101  committed the changes for the matric validation bug fixes

**Comment by bhermann** [comment]
Project closed
