### ISSUE TITLE
Testing - Back-end

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#49]
**Description**
Testing the application back-end
 
**Status **
Develop first test case for query function using PlaySpec as a testing style.

**Comment by chinmayk1613** [comment]
Update_29.01.2020
----- Understood the basic concept like-Test Suits, Testing Styles.
----- Observed all testing styles that are already defined in scalaTest.
----- Need to decide which testig style we used in the project.

**Comment by Orkanelf** [comment]
Same for me, but @chinmayk1613 are you also able to test the controller? Like the HomeController?

Greetings

**Comment by chinmayk1613** [comment]
Not Actually ...before testing real class was just try to make dummy test just to check how test case made and how it is giving result....tomorow we can try with home controller....with dummy test case it givin me result something like.....success. 0 test cases success.....need to check on this tomorrow...

Parallel to this was also checking mocking technique which also gives easy access to test functions with custom test cases...

**Comment by chinmayk1613** [comment]
Update_12.02.2019
----- Understood basics while creating the test cases.
----- Develop the test case whether the result is successfully coming or not using query method.
----- In a preparation to make test case to check URL testing, Syntax Check testing.

**Comment by bhermann** [comment]
Project closed
