### ISSUE TITLE
FrontController: The method takes a value that is controlled by the client

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-webapp#51]
#### Currently on:
+ **Commit**:  e7bcf2d28ea9cf796136e265c6c1db129fe31bc8
+ **File**:    [app/controllers/FrontController.scala](https://github.com/delphi-hub/delphi-webapp/blob/e7bcf2d28ea9cf796136e265c6c1db129fe31bc8/app/controllers/FrontController.scala)
+ **LineNum**: [33](https://github.com/delphi-hub/delphi-webapp/blob/e7bcf2d28ea9cf796136e265c6c1db129fe31bc8/app/controllers/FrontController.scala#L33)

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #69 . Issue doesn`t appear in the latest version.
