### ISSUE TITLE
HomeController:132 - The method takes a value that is controlled by the client

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-webapp#53]
#### Currently on:
+ **Commit**:  e7bcf2d28ea9cf796136e265c6c1db129fe31bc8
+ **File**:    [app/controllers/HomeController.scala](https://github.com/delphi-hub/delphi-webapp/blob/e7bcf2d28ea9cf796136e265c6c1db129fe31bc8/app/controllers/HomeController.scala)
+ **LineNum**: [132](https://github.com/delphi-hub/delphi-webapp/blob/e7bcf2d28ea9cf796136e265c6c1db129fe31bc8/app/controllers/HomeController.scala#L132)

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #69 . Issue doesn`t appear in the latest version.
