### ISSUE TITLE
Allow string values in queries

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-webapp#54]
**Is your feature request related to a problem? Please describe.**
Version 0.9.5 of the API supports searching for string values. The current UI prevents users from composing such queries.

**Describe the solution you'd like**
Allow for users to enter string data. The application should properly incorporate them into the query.

**Describe alternatives you've considered**
non

**Additional context**
See screenshot.
<img width="462" alt="Screenshot 2020-01-24 at 15 34 49" src="https://user-images.githubusercontent.com/1974799/73076868-4bd2c000-3ebf-11ea-9931-464a508132ad.png">

**Comment by syam595** [comment]
Discussed with Ben. No need to consider the data type of the specific metric at this point since the datatype expected for the metric is not returned as part of the API feature. 
Will enable string values by removing number only constraint.

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in #64 .
