### ISSUE TITLE
Header bar has an offset to the top of the page

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-webapp#55]
**Describe the bug**
When opening the web application the header bar has a distance to the top of the browser window. I don't think this is intended.

**To Reproduce**
1. Open web application 

**Expected behavior**
The header bar should stick to the very top of the page.

**Screenshots**
<img width="183" alt="Screenshot 2020-01-24 at 15 40 31" src="https://user-images.githubusercontent.com/1974799/73077578-bcc6a780-3ec0-11ea-8a6e-877b9855049e.png">

**Affected components (if known)**
webapp

**Desktop (please complete the following information, if relevant):**
Google Chrome Version 79.0.3945.117 (Official Build) (64-bit)

**Smartphone (please complete the following information, if relevant):**
n/a

**Additional context**
n/a

**Comment by SViktorS** [comment]
Fixed. Will be part of the next pull request "validation"
