### ISSUE TITLE
Queries are removed from the query box once `search` is processed.

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-webapp#57]
**Describe the bug**
The query composed by the user is lost after the search is performed.

**To Reproduce**
1. Go to the webapp.
2. Enter a query.
3. Click 'Start Search'.
4. Wait for the search to be performed

**Expected behavior**
The query stays in the field.

**Screenshots**
n/a

**Affected components (if known)**
webapp

**Desktop (please complete the following information, if relevant):**
n/a

**Smartphone (please complete the following information, if relevant):**
n/a

**Additional context**
Users might want to review and refine their queries. This will not be possible when the query is deleted from the field.

**Comment by SViktorS** [comment]
Fixed. Will be part of the next pull request "validation".
