### ISSUE TITLE
Dynamic table with multiple result columns for multiple queries at a time

### ISSUE THREAD

**Issue by Subbup101** [delphi-hub/delphi-webapp#62]
Currently there is only one results column which will not support for multiple query search.

**Comment by Subbup101** [comment]
Implemented functionality which generates dynamic columns in a table for multiple queries. There are minor design changes pending related to it. Will be pushed in next PR.

**Comment by Shashank-KanakapuraSrivatsa** [comment]
Addressed in PR #67
