### ISSUE TITLE
Bug fixes in Auto-completion feature and error handling in More Information page

### ISSUE THREAD

**Issue by Shashank-KanakapuraSrivatsa** [delphi-hub/delphi-webapp#71]
**Description**
1. In **Auto-completion**, the cursor is not placed back in the text-area, after selecting from the suggested options. 
2. In **More Information** page, the errors should re-direct the user back to the landing page or to "404 - Page not found"

**Comment by syam595** [comment]
Committed the changes for Auto completion bug fix

**Comment by syam595** [comment]
@Subbup101   committed the changes for the matric validation bug fixes

**Comment by bhermann** [comment]
Project closed
